// Generated by CoffeeScript 1.6.3
var Fluid;

module.exports = Fluid = (function() {
  Fluid.prototype.route = null;

  Fluid.prototype.dependency = null;

  function Fluid(route, url) {
    this.route = route;
    this.url = url;
    if (this.route.dependency != null) {
      this.dependency = this.route.computed_dependency(this.url);
    }
  }

  Fluid.prototype.run = function(url, done) {
    return this.req = this.route.run(this.url, done);
  };

  Fluid.prototype.destroy = function(done) {
    if (this.req != null) {
      return this.route.destroy(this.req, done);
    }
  };

  return Fluid;

})();
