// Generated by CoffeeScript 1.6.3
var Flow, Route, Router;

Route = require('./route');

Flow = require('./flow');

module.exports = Router = (function() {
  Router.prototype.mode = null;

  Router.prototype.flow = null;

  Router.prototype.routes = null;

  function Router(mode) {
    this.mode = mode;
    this.routes = [];
    if (this.mode != null) {
      this.flow = new Flow(this);
    }
  }

  Router.prototype.get = function(pattern, run, destroy, dependency) {
    var route;
    route = new Route(pattern, run, destroy, dependency);
    this.routes.push(route);
    return route;
  };

  Router.prototype.route = function(url) {
    var route, _i, _len, _ref;
    url = '/' + url.replace(/^[\/]+|[\/]+$/m, '');
    _ref = this.routes;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      route = _ref[_i];
      if (route.matcher.test(url)) {
        return this.run(route, url);
      }
    }
    throw new Error("Route not found for url '" + url + "'");
  };

  Router.prototype.run = function(route, url) {
    if (this.mode != null) {
      this.flow.run(url, route);
    } else {
      route.run(url);
    }
    return route;
  };

  return Router;

})();
